# Generated by Django 5.2.4 on 2025-07-19 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('compensation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='leve_note',
            new_name='leaveNote',
        ),
        migrations.AlterModelOptions(
            name='leavenote',
            options={'verbose_name': 'Leave Note', 'verbose_name_plural': 'Leve Notes'},
        ),
        migrations.RemoveField(
            model_name='jobtitle',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='api.jobtitle'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
        migrations.DeleteModel(
            name='pay_roll',
        ),
    ]
