# Generated by Django 5.2.4 on 2025-08-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendance_delete_payroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
