# Generated by Django 5.2.4 on 2025-07-19 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_payroll_rename_leve_note_leavenote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='api.payroll'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavenote',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_note', to='api.employee'),
        ),
    ]
