# Generated by Django 5.2.4 on 2025-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='termintion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
