# Generated by Django 5.2.4 on 2025-07-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_salary_alter_employee_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavenote',
            options={'verbose_name': 'Leave Note', 'verbose_name_plural': 'Leave Notes'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='api.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
