# Generated by Django 5.2.4 on 2025-08-17 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_status_employee_termintion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavenote',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=255),
        ),
    ]
