# Generated by Django 5.2.4 on 2025-08-17 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_leavenote_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='termintion_date',
            new_name='termination_date',
        ),
    ]
