# Generated by Django 5.2.4 on 2025-08-17 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_termintion_date_employee_termination_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('exit_type', models.CharField(choices=[('voluntary', 'Voluntary'), ('involuntary', 'Involuntary'), ('end_of_contract', 'End of contract')], max_length=255)),
                ('final_settlement_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit', to='api.employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_exits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exit',
                'verbose_name_plural': 'Exits',
                'ordering': ['-exit_date', '-created_at'],
            },
        ),
    ]
