# Generated by Django 5.2.4 on 2025-08-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('binding', 'Binding'), ('notice', 'On Notice Period'), ('inactive', 'Inactive')], default='binding', max_length=20),
        ),
    ]
