# Generated by Django 5.2.4 on 2025-08-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
