# Generated by Django 5.2.4 on 2025-08-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'pending'), ('notice', 'On Notice Period'), ('inactive', 'Inactive')], default='binding', max_length=20),
        ),
    ]
