# Generated by Django 5.2.4 on 2025-08-12 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_attendance'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='attendance__employe_08d913_idx',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_minutes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
