# Generated by Django 5.2.4 on 2025-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exit'),
        ('attendance', '0003_alter_attendance_check_in'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['employee'], name='attendance_employee_idx'),
        ),
    ]
