# Generated by Django 5.2.4 on 2025-08-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exit'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'year', 'month'], name='hr_payroll_employe_44eb46_idx'),
        ),
    ]
