# Generated by Django 5.2.4 on 2025-08-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exit'),
        ('hr', '0002_payroll_hr_payroll_employe_44eb46_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payroll',
            name='hr_payroll_employe_44eb46_idx',
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['year', 'month'], name='payroll_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee'], name='payroll_employee_idx'),
        ),
    ]
