# Generated by Django 5.2.4 on 2025-08-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_exit'),
        ('hr', '0003_remove_payroll_hr_payroll_employe_44eb46_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.RemoveIndex(
            model_name='payroll',
            name='payroll_year_month_idx',
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['-year', '-month'], name='payroll_year_month_idx'),
        ),
    ]
